title: Akshay Appani
#logo: /assets/img/headshot_circle.png
#description: Data Analyst | ML Enthusiast | Data Science | M S in Business Analytics
#show_downloads: true
theme: pages-themes.github.io/hacker/
